crawler:
  build: .
  # links:
  #   - db
  ports:
    - "6060:6060"
  ulimits:
    nofile:
      hard: 50000
      soft: 50000
  volumes:
    - /out:/inv




# db:
#   image: postgres
#   environment:
#     - POSTGRES_PASSWORD=centralised
#     - POSTGRES_USER=alexander
#     - POSTGRES_DB=btc
